//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 01:59:56 AM WEST 
//


package project.com.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Topic_QNAME = new QName("http://schema/", "topic");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Topictype }
     * 
     */
    public Topictype createTopictype() {
        return new Topictype();
    }

    /**
     * Create an instance of {@link Newstype }
     * 
     */
    public Newstype createNewstype() {
        return new Newstype();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Topictype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://schema/", name = "topic")
    public JAXBElement<Topictype> createTopic(Topictype value) {
        return new JAXBElement<Topictype>(_Topic_QNAME, Topictype.class, null, value);
    }

}
