<wsdl:definitions xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://subscribe.org/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http" name="IUnsubscribeService" targetNamespace="http://subscribe.org/">
<wsdl:types>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://subscribe.org/" elementFormDefault="unqualified" targetNamespace="http://subscribe.org/" version="1.0">
<xs:element name="unsubscribeUser" type="tns:unsubscribeUser"/>
<xs:element name="unsubscribeUserResponse" type="tns:unsubscribeUserResponse"/>
<xs:complexType name="unsubscribeUser">
<xs:sequence>
<xs:element minOccurs="0" name="arg0" type="xs:string"/>
</xs:sequence>
</xs:complexType>
<xs:complexType name="unsubscribeUserResponse">
<xs:sequence>
<xs:element minOccurs="0" name="return" type="xs:string"/>
</xs:sequence>
</xs:complexType>
</xs:schema>
</wsdl:types>
<wsdl:message name="unsubscribeUser">
<wsdl:part element="tns:unsubscribeUser" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:message name="unsubscribeUserResponse">
<wsdl:part element="tns:unsubscribeUserResponse" name="parameters"></wsdl:part>
</wsdl:message>
<wsdl:portType name="IUnsubscribe">
<wsdl:operation name="unsubscribeUser">
<wsdl:input message="tns:unsubscribeUser" name="unsubscribeUser"></wsdl:input>
<wsdl:output message="tns:unsubscribeUserResponse" name="unsubscribeUserResponse"></wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="IUnsubscribeServiceSoapBinding" type="tns:IUnsubscribe">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="unsubscribeUser">
<soap:operation soapAction="" style="document"/>
<wsdl:input name="unsubscribeUser">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="unsubscribeUserResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="IUnsubscribeService">
<wsdl:port binding="tns:IUnsubscribeServiceSoapBinding" name="IUnsubscribePort">
<soap:address location="http://localhost:8082/soapUnsubscribe"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>