//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 01:59:56 AM WEST 
//


package aux;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for newstype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="newstype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://schema/}stringtype"/>
 *         &lt;element name="url" type="{http://schema/}uritype"/>
 *         &lt;element name="highlights" type="{http://schema/}stringtype" maxOccurs="unbounded"/>
 *         &lt;element name="date" type="{http://schema/}datetype"/>
 *         &lt;element name="author" type="{http://schema/}stringtype"/>
 *         &lt;element name="content" type="{http://schema/}stringtype"/>
 *         &lt;element name="photos" type="{http://schema/}uritype" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="video" type="{http://schema/}uritype" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="newsid" use="required" type="{http://schema/}newsidtype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "newstype", propOrder = {
    "title",
    "url",
    "highlights",
    "date",
    "author",
    "content",
    "photos",
    "video"
})
public class Newstype {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String url;
    @XmlElement(required = true)
    protected List<String> highlights = new ArrayList<String>();
    @XmlElement(required = true)
    protected XMLGregorianCalendar date;
    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String content;
    protected List<String> photos = new ArrayList<String>();
    protected List<String> video = new ArrayList<String>();
    @XmlAttribute(name = "newsid", required = true)
    protected String newsid;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }
    
    public void setHighLights(List<String> value) {
    	
        this.highlights = value;
    }
    
public void setImages(List<String> value) {
    	
        this.photos = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the highlights property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the highlights property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHighlights().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getHighlights() {
        if (highlights == null) {
            highlights = new ArrayList<String>();
        }
        return this.highlights;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the photos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the photos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPhotos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPhotos() {
        if (photos == null) {
            photos = new ArrayList<String>();
        }
        return this.photos;
    }

    /**
     * Gets the value of the video property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the video property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVideo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getVideo() {
        if (video == null) {
            video = new ArrayList<String>();
        }
        return this.video;
    }

    /**
     * Gets the value of the newsid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewsid() {
        return newsid;
    }

    /**
     * Sets the value of the newsid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewsid(String value) {
        this.newsid = value;
    }

}
