//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.14 at 01:59:56 AM WEST 
//


package aux;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for topictype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="topictype">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="topicname" type="{http://schema/}topicnametype"/>
 *         &lt;element name="news" type="{http://schema/}newstype" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="topicid" use="required" type="{http://schema/}topicidtype" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "topictype", propOrder = {
    "topicname",
    "news"
})

@XmlRootElement(name = "topic")

public class Topictype {

    @XmlElement(required = true)
    protected Topicnametype topicname;
    @XmlElement(required = true)
    protected List<Newstype> news = new ArrayList<Newstype>();
    @XmlAttribute(name = "topicid", required = true)
    protected String topicid;

    /**
     * Gets the value of the topicname property.
     * 
     * @return
     *     possible object is
     *     {@link Topicnametype }
     *     
     */
    public Topicnametype getTopicname() {
        return topicname;
    }

    /**
     * Sets the value of the topicname property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topicnametype }
     *     
     */
    public void setTopicname(Topicnametype value) {
        this.topicname = value;
    }

    /**
     * Gets the value of the news property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the news property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNews().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Newstype }
     * 
     * 
     */
    public List<Newstype> getNews() {
        if (news == null) {
            news = new ArrayList<Newstype>();
        }
        return this.news;
    }
    
    
    public void setNewsList(List<Newstype> value) {
        this.news = value;
        
    }

    /**
     * Gets the value of the topicid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTopicid() {
        return topicid;
    }

    /**
     * Sets the value of the topicid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTopicid(String value) {
        this.topicid = value;
    }

}
