package org.subscribe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2014-12-23T18:08:04.393Z
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://subscribe.org/", name = "IAddNews")
@XmlSeeAlso({ObjectFactory.class})
public interface IAddNews {

    @WebMethod
    @RequestWrapper(localName = "addNews", targetNamespace = "http://subscribe.org/", className = "org.subscribe.AddNews")
    @ResponseWrapper(localName = "addNewsResponse", targetNamespace = "http://subscribe.org/", className = "org.subscribe.AddNewsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String addNews(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
