package org.subscribe;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2014-12-23T18:08:04.456Z
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "IAddNewsService", 
                  wsdlLocation = "addNews.wsdl",
                  targetNamespace = "http://subscribe.org/") 
public class IAddNewsService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://subscribe.org/", "IAddNewsService");
    public final static QName IAddNewsPort = new QName("http://subscribe.org/", "IAddNewsPort");
    static {
        URL url = IAddNewsService.class.getResource("addNews.wsdl");
        if (url == null) {
            url = IAddNewsService.class.getClassLoader().getResource("addNews.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(IAddNewsService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "addNews.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public IAddNewsService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IAddNewsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IAddNewsService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAddNewsService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAddNewsService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IAddNewsService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns IAddNews
     */
    @WebEndpoint(name = "IAddNewsPort")
    public IAddNews getIAddNewsPort() {
        return super.getPort(IAddNewsPort, IAddNews.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAddNews
     */
    @WebEndpoint(name = "IAddNewsPort")
    public IAddNews getIAddNewsPort(WebServiceFeature... features) {
        return super.getPort(IAddNewsPort, IAddNews.class, features);
    }

}
