package org.subscribe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2014-12-21T20:53:09.718Z
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://subscribe.org/", name = "ISubscribe")
@XmlSeeAlso({ObjectFactory.class})
public interface ISubscribe {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://subscribe.org/", className = "org.subscribe.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://subscribe.org/", className = "org.subscribe.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
