package org.subscribe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2014-12-23T05:30:47.356Z
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://subscribe.org/", name = "ISubscribe")
@XmlSeeAlso({ObjectFactory.class})
public interface ISubscribe {

    @WebMethod
    @RequestWrapper(localName = "subscribeUser", targetNamespace = "http://subscribe.org/", className = "org.subscribe.SubscribeUser")
    @ResponseWrapper(localName = "subscribeUserResponse", targetNamespace = "http://subscribe.org/", className = "org.subscribe.SubscribeUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public org.subscribe.Info subscribeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
