package org.subscribe;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2014-12-23T05:30:54.802Z
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://subscribe.org/", name = "IUnsubscribe")
@XmlSeeAlso({ObjectFactory.class})
public interface IUnsubscribe {

    @WebMethod
    @RequestWrapper(localName = "unsubscribeUser", targetNamespace = "http://subscribe.org/", className = "org.subscribe.UnsubscribeUser")
    @ResponseWrapper(localName = "unsubscribeUserResponse", targetNamespace = "http://subscribe.org/", className = "org.subscribe.UnsubscribeUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String unsubscribeUser(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
